# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1242, 675)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_function = QtWidgets.QWidget(self.centralwidget)
        self.widget_function.setGeometry(QtCore.QRect(10, 40, 131, 611))
        self.widget_function.setObjectName("widget_function")
        self.pushButton_diva = QtWidgets.QPushButton(self.widget_function)
        self.pushButton_diva.setGeometry(QtCore.QRect(10, 60, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_diva.setFont(font)
        self.pushButton_diva.setObjectName("pushButton_diva")
        self.pushButton_diagnosis = QtWidgets.QPushButton(self.widget_function)
        self.pushButton_diagnosis.setGeometry(QtCore.QRect(10, 120, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_diagnosis.setFont(font)
        self.pushButton_diagnosis.setObjectName("pushButton_diagnosis")
        self.pushButton_nm = QtWidgets.QPushButton(self.widget_function)
        self.pushButton_nm.setGeometry(QtCore.QRect(10, 180, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_nm.setFont(font)
        self.pushButton_nm.setObjectName("pushButton_nm")
        self.pushButton_signal = QtWidgets.QPushButton(self.widget_function)
        self.pushButton_signal.setGeometry(QtCore.QRect(10, 240, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_signal.setFont(font)
        self.pushButton_signal.setObjectName("pushButton_signal")
        self.label = QtWidgets.QLabel(self.widget_function)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_read_version = QtWidgets.QPushButton(self.widget_function)
        self.pushButton_read_version.setGeometry(QtCore.QRect(10, 300, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_read_version.setFont(font)
        self.pushButton_read_version.setObjectName("pushButton_read_version")
        self.pushButton_car_scene = QtWidgets.QPushButton(self.widget_function)
        self.pushButton_car_scene.setGeometry(QtCore.QRect(10, 420, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_car_scene.setFont(font)
        self.pushButton_car_scene.setObjectName("pushButton_car_scene")
        self.pushButton_car_action = QtWidgets.QPushButton(self.widget_function)
        self.pushButton_car_action.setGeometry(QtCore.QRect(10, 480, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_car_action.setFont(font)
        self.pushButton_car_action.setObjectName("pushButton_car_action")
        self.pushButton_release_file_format_check = QtWidgets.QPushButton(self.widget_function)
        self.pushButton_release_file_format_check.setGeometry(QtCore.QRect(10, 540, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_release_file_format_check.setFont(font)
        self.pushButton_release_file_format_check.setObjectName("pushButton_release_file_format_check")
        self.pushButton_car_dtc = QtWidgets.QPushButton(self.widget_function)
        self.pushButton_car_dtc.setGeometry(QtCore.QRect(10, 360, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_car_dtc.setFont(font)
        self.pushButton_car_dtc.setObjectName("pushButton_car_dtc")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(150, 40, 491, 611))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_diva = QtWidgets.QWidget()
        self.page_diva.setObjectName("page_diva")
        self.label_2 = QtWidgets.QLabel(self.page_diva)
        self.label_2.setGeometry(QtCore.QRect(80, 20, 301, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.comboBox_function = QtWidgets.QComboBox(self.page_diva)
        self.comboBox_function.setGeometry(QtCore.QRect(10, 60, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_function.setFont(font)
        self.comboBox_function.setObjectName("comboBox_function")
        self.comboBox_function.addItem("")
        self.comboBox_function.addItem("")
        self.comboBox_function.addItem("")
        self.comboBox_function.addItem("")
        self.comboBox_function.addItem("")
        self.comboBox_function.addItem("")
        self.comboBox_function.addItem("")
        self.pushButton_diva_test = QtWidgets.QPushButton(self.page_diva)
        self.pushButton_diva_test.setGeometry(QtCore.QRect(350, 60, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_diva_test.setFont(font)
        self.pushButton_diva_test.setObjectName("pushButton_diva_test")
        self.groupBox = QtWidgets.QGroupBox(self.page_diva)
        self.groupBox.setGeometry(QtCore.QRect(0, 410, 481, 181))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.lcdNumber_error = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_error.setGeometry(QtCore.QRect(360, 110, 101, 31))
        self.lcdNumber_error.setObjectName("lcdNumber_error")
        self.lcdNumber_pass = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_pass.setGeometry(QtCore.QRect(360, 70, 101, 31))
        self.lcdNumber_pass.setObjectName("lcdNumber_pass")
        self.lcdNumber_total = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_total.setGeometry(QtCore.QRect(360, 30, 101, 31))
        self.lcdNumber_total.setObjectName("lcdNumber_total")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(290, 29, 54, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(290, 70, 54, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(290, 115, 54, 21))
        self.label_8.setObjectName("label_8")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(10, 20, 271, 141))
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit_show_diva_test_file = QtWidgets.QLineEdit(self.page_diva)
        self.lineEdit_show_diva_test_file.setGeometry(QtCore.QRect(10, 10, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_show_diva_test_file.setFont(font)
        self.lineEdit_show_diva_test_file.setObjectName("lineEdit_show_diva_test_file")
        self.pushButton_diva_select = QtWidgets.QPushButton(self.page_diva)
        self.pushButton_diva_select.setGeometry(QtCore.QRect(350, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_diva_select.setFont(font)
        self.pushButton_diva_select.setObjectName("pushButton_diva_select")
        self.stackedWidget.addWidget(self.page_diva)
        self.page_car_scene = QtWidgets.QWidget()
        self.page_car_scene.setObjectName("page_car_scene")
        self.pushButton_load_kvaser_file = QtWidgets.QPushButton(self.page_car_scene)
        self.pushButton_load_kvaser_file.setGeometry(QtCore.QRect(330, 200, 121, 41))
        self.pushButton_load_kvaser_file.setObjectName("pushButton_load_kvaser_file")
        self.lineEdit_load_kvaser_file = QtWidgets.QLineEdit(self.page_car_scene)
        self.lineEdit_load_kvaser_file.setGeometry(QtCore.QRect(30, 200, 291, 91))
        self.lineEdit_load_kvaser_file.setObjectName("lineEdit_load_kvaser_file")
        self.label_9 = QtWidgets.QLabel(self.page_car_scene)
        self.label_9.setGeometry(QtCore.QRect(30, 20, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.textEdit_car_scene = QtWidgets.QTextEdit(self.page_car_scene)
        self.textEdit_car_scene.setGeometry(QtCore.QRect(30, 320, 431, 211))
        self.textEdit_car_scene.setObjectName("textEdit_car_scene")
        self.label_10 = QtWidgets.QLabel(self.page_car_scene)
        self.label_10.setGeometry(QtCore.QRect(30, 90, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.page_car_scene)
        self.label_11.setGeometry(QtCore.QRect(30, 150, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdit_filter_app_node = QtWidgets.QLineEdit(self.page_car_scene)
        self.lineEdit_filter_app_node.setGeometry(QtCore.QRect(120, 90, 121, 31))
        self.lineEdit_filter_app_node.setObjectName("lineEdit_filter_app_node")
        self.lineEdit_filter_nm_node = QtWidgets.QLineEdit(self.page_car_scene)
        self.lineEdit_filter_nm_node.setGeometry(QtCore.QRect(120, 140, 121, 31))
        self.lineEdit_filter_nm_node.setObjectName("lineEdit_filter_nm_node")
        self.pushButton_read_file = QtWidgets.QPushButton(self.page_car_scene)
        self.pushButton_read_file.setGeometry(QtCore.QRect(330, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_read_file.setFont(font)
        self.pushButton_read_file.setObjectName("pushButton_read_file")
        self.stackedWidget.addWidget(self.page_car_scene)
        self.page_diagnosis = QtWidgets.QWidget()
        self.page_diagnosis.setObjectName("page_diagnosis")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_diagnosis)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 130, 451, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_diag_session = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_diag_session.setGeometry(QtCore.QRect(20, 20, 221, 31))
        self.comboBox_diag_session.setObjectName("comboBox_diag_session")
        self.comboBox_diag_session.addItem("")
        self.comboBox_diag_session.addItem("")
        self.comboBox_diag_session.addItem("")
        self.comboBox_diag_session.addItem("")
        self.pushButton_diag_session = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_diag_session.setGeometry(QtCore.QRect(330, 20, 91, 31))
        self.pushButton_diag_session.setObjectName("pushButton_diag_session")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_diagnosis)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 210, 451, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.comboBox_diag_request_seed = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_diag_request_seed.setGeometry(QtCore.QRect(20, 20, 221, 31))
        self.comboBox_diag_request_seed.setObjectName("comboBox_diag_request_seed")
        self.comboBox_diag_request_seed.addItem("")
        self.comboBox_diag_request_seed.addItem("")
        self.comboBox_diag_request_seed.addItem("")
        self.comboBox_diag_request_seed.addItem("")
        self.pushButton_diag_request_seed = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_diag_request_seed.setGeometry(QtCore.QRect(330, 20, 91, 31))
        self.pushButton_diag_request_seed.setObjectName("pushButton_diag_request_seed")
        self.comboBox_diag_send_key = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_diag_send_key.setGeometry(QtCore.QRect(20, 60, 221, 31))
        self.comboBox_diag_send_key.setObjectName("comboBox_diag_send_key")
        self.comboBox_diag_send_key.addItem("")
        self.comboBox_diag_send_key.addItem("")
        self.comboBox_diag_send_key.addItem("")
        self.comboBox_diag_send_key.addItem("")
        self.pushButton_diag_send_key = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_diag_send_key.setGeometry(QtCore.QRect(330, 60, 91, 31))
        self.pushButton_diag_send_key.setObjectName("pushButton_diag_send_key")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_diagnosis)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 320, 451, 151))
        self.groupBox_5.setObjectName("groupBox_5")
        self.comboBox_diag_other_service = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_diag_other_service.setGeometry(QtCore.QRect(20, 20, 221, 31))
        self.comboBox_diag_other_service.setObjectName("comboBox_diag_other_service")
        self.comboBox_diag_other_service.addItem("")
        self.comboBox_diag_other_service.addItem("")
        self.comboBox_diag_other_service.addItem("")
        self.comboBox_diag_other_service.addItem("")
        self.comboBox_diag_other_service.addItem("")
        self.comboBox_diag_other_service.addItem("")
        self.comboBox_diag_other_service.addItem("")
        self.comboBox_diag_other_service.addItem("")
        self.comboBox_diag_other_service.addItem("")
        self.comboBox_diag_other_service.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_4.setGeometry(QtCore.QRect(20, 60, 221, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_5.setGeometry(QtCore.QRect(20, 100, 221, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.pushButton_diag_send_service = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_diag_send_service.setGeometry(QtCore.QRect(330, 30, 91, 81))
        self.pushButton_diag_send_service.setObjectName("pushButton_diag_send_service")
        self.groupBox_8 = QtWidgets.QGroupBox(self.page_diagnosis)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 470, 451, 131))
        self.groupBox_8.setObjectName("groupBox_8")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox_8)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 30, 401, 91))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_diag_title = QtWidgets.QLabel(self.page_diagnosis)
        self.label_diag_title.setGeometry(QtCore.QRect(10, 20, 451, 41))
        self.label_diag_title.setObjectName("label_diag_title")
        self.pushButton_diag_configer_file = QtWidgets.QPushButton(self.page_diagnosis)
        self.pushButton_diag_configer_file.setGeometry(QtCore.QRect(30, 80, 101, 31))
        self.pushButton_diag_configer_file.setObjectName("pushButton_diag_configer_file")
        self.radioButton_phy_address = QtWidgets.QRadioButton(self.page_diagnosis)
        self.radioButton_phy_address.setGeometry(QtCore.QRect(340, 80, 89, 16))
        self.radioButton_phy_address.setObjectName("radioButton_phy_address")
        self.radioButton_device_online = QtWidgets.QRadioButton(self.page_diagnosis)
        self.radioButton_device_online.setGeometry(QtCore.QRect(340, 100, 89, 21))
        self.radioButton_device_online.setObjectName("radioButton_device_online")
        self.stackedWidget.addWidget(self.page_diagnosis)
        self.page_nm = QtWidgets.QWidget()
        self.page_nm.setObjectName("page_nm")
        self.label_4 = QtWidgets.QLabel(self.page_nm)
        self.label_4.setGeometry(QtCore.QRect(60, 60, 421, 20))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_nm)
        self.page_signal = QtWidgets.QWidget()
        self.page_signal.setObjectName("page_signal")
        self.groupBox_chery_sw = QtWidgets.QGroupBox(self.page_signal)
        self.groupBox_chery_sw.setGeometry(QtCore.QRect(10, 290, 471, 131))
        self.groupBox_chery_sw.setObjectName("groupBox_chery_sw")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_chery_sw)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 80, 211, 31))
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.radioButton_dow_off = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_dow_off.setGeometry(QtCore.QRect(140, 10, 61, 16))
        self.radioButton_dow_off.setObjectName("radioButton_dow_off")
        self.radioButton_dow_on = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_dow_on.setGeometry(QtCore.QRect(70, 10, 61, 16))
        self.radioButton_dow_on.setObjectName("radioButton_dow_on")
        self.label_19 = QtWidgets.QLabel(self.groupBox_12)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_chery_sw)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 50, 211, 31))
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.radioButton_rcw_off = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_rcw_off.setGeometry(QtCore.QRect(140, 10, 61, 16))
        self.radioButton_rcw_off.setObjectName("radioButton_rcw_off")
        self.radioButton_rcw_on = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_rcw_on.setGeometry(QtCore.QRect(70, 10, 61, 16))
        self.radioButton_rcw_on.setObjectName("radioButton_rcw_on")
        self.label_18 = QtWidgets.QLabel(self.groupBox_11)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_chery_sw)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 20, 211, 31))
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.radioButton_bsd_off = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_bsd_off.setGeometry(QtCore.QRect(140, 10, 61, 16))
        self.radioButton_bsd_off.setObjectName("radioButton_bsd_off")
        self.radioButton_bsd_on = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_bsd_on.setGeometry(QtCore.QRect(70, 10, 61, 16))
        self.radioButton_bsd_on.setObjectName("radioButton_bsd_on")
        self.label_15 = QtWidgets.QLabel(self.groupBox_10)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.pushButton_send_ihu_sw = QtWidgets.QPushButton(self.groupBox_chery_sw)
        self.pushButton_send_ihu_sw.setGeometry(QtCore.QRect(310, 30, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_send_ihu_sw.setFont(font)
        self.pushButton_send_ihu_sw.setObjectName("pushButton_send_ihu_sw")
        self.textBrowser_ihu_sw_message = QtWidgets.QTextBrowser(self.page_signal)
        self.textBrowser_ihu_sw_message.setGeometry(QtCore.QRect(10, 60, 471, 121))
        self.textBrowser_ihu_sw_message.setObjectName("textBrowser_ihu_sw_message")
        self.groupBox_ctcs_sw = QtWidgets.QGroupBox(self.page_signal)
        self.groupBox_ctcs_sw.setEnabled(True)
        self.groupBox_ctcs_sw.setGeometry(QtCore.QRect(10, 430, 471, 151))
        self.groupBox_ctcs_sw.setObjectName("groupBox_ctcs_sw")
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_ctcs_sw)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 80, 211, 31))
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.radioButton_ctcs_dow_off = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_ctcs_dow_off.setGeometry(QtCore.QRect(140, 10, 61, 16))
        self.radioButton_ctcs_dow_off.setObjectName("radioButton_ctcs_dow_off")
        self.radioButton_ctcs_dow_on = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_ctcs_dow_on.setGeometry(QtCore.QRect(70, 10, 61, 16))
        self.radioButton_ctcs_dow_on.setObjectName("radioButton_ctcs_dow_on")
        self.label_20 = QtWidgets.QLabel(self.groupBox_14)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_ctcs_sw)
        self.groupBox_15.setGeometry(QtCore.QRect(10, 50, 211, 31))
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.radioButton_ctcs_cvw_off = QtWidgets.QRadioButton(self.groupBox_15)
        self.radioButton_ctcs_cvw_off.setGeometry(QtCore.QRect(140, 10, 61, 16))
        self.radioButton_ctcs_cvw_off.setObjectName("radioButton_ctcs_cvw_off")
        self.radioButton_ctcs_cvw_on = QtWidgets.QRadioButton(self.groupBox_15)
        self.radioButton_ctcs_cvw_on.setGeometry(QtCore.QRect(70, 10, 61, 16))
        self.radioButton_ctcs_cvw_on.setObjectName("radioButton_ctcs_cvw_on")
        self.label_21 = QtWidgets.QLabel(self.groupBox_15)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_ctcs_sw)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 20, 211, 31))
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.radioButton_ctcs_bsd_off = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_ctcs_bsd_off.setGeometry(QtCore.QRect(140, 10, 61, 16))
        self.radioButton_ctcs_bsd_off.setObjectName("radioButton_ctcs_bsd_off")
        self.radioButton_ctcs_bsd_on = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_ctcs_bsd_on.setGeometry(QtCore.QRect(70, 10, 61, 16))
        self.radioButton_ctcs_bsd_on.setObjectName("radioButton_ctcs_bsd_on")
        self.label_16 = QtWidgets.QLabel(self.groupBox_9)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.pushButton_send_ctcs_ihu_sw = QtWidgets.QPushButton(self.groupBox_ctcs_sw)
        self.pushButton_send_ctcs_ihu_sw.setGeometry(QtCore.QRect(310, 50, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_send_ctcs_ihu_sw.setFont(font)
        self.pushButton_send_ctcs_ihu_sw.setObjectName("pushButton_send_ctcs_ihu_sw")
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_ctcs_sw)
        self.groupBox_17.setGeometry(QtCore.QRect(10, 110, 211, 31))
        self.groupBox_17.setTitle("")
        self.groupBox_17.setObjectName("groupBox_17")
        self.radioButton_ctcs_rcw_off = QtWidgets.QRadioButton(self.groupBox_17)
        self.radioButton_ctcs_rcw_off.setGeometry(QtCore.QRect(140, 10, 61, 16))
        self.radioButton_ctcs_rcw_off.setObjectName("radioButton_ctcs_rcw_off")
        self.radioButton_ctcs_rcw_on = QtWidgets.QRadioButton(self.groupBox_17)
        self.radioButton_ctcs_rcw_on.setGeometry(QtCore.QRect(70, 10, 61, 16))
        self.radioButton_ctcs_rcw_on.setObjectName("radioButton_ctcs_rcw_on")
        self.label_22 = QtWidgets.QLabel(self.groupBox_17)
        self.label_22.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_5 = QtWidgets.QLabel(self.page_signal)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.groupBox_18 = QtWidgets.QGroupBox(self.page_signal)
        self.groupBox_18.setGeometry(QtCore.QRect(10, 200, 471, 71))
        self.groupBox_18.setObjectName("groupBox_18")
        self.radioButton_chery_t1d_2 = QtWidgets.QRadioButton(self.groupBox_18)
        self.radioButton_chery_t1d_2.setGeometry(QtCore.QRect(10, 30, 131, 16))
        self.radioButton_chery_t1d_2.setObjectName("radioButton_chery_t1d_2")
        self.radioButton_chery_ctcs_2 = QtWidgets.QRadioButton(self.groupBox_18)
        self.radioButton_chery_ctcs_2.setGeometry(QtCore.QRect(310, 30, 89, 16))
        self.radioButton_chery_ctcs_2.setObjectName("radioButton_chery_ctcs_2")
        self.stackedWidget.addWidget(self.page_signal)
        self.page_car_action = QtWidgets.QWidget()
        self.page_car_action.setObjectName("page_car_action")
        self.label_12 = QtWidgets.QLabel(self.page_car_action)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_car_action)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 60, 121, 91))
        self.groupBox_6.setObjectName("groupBox_6")
        self.radioButton_chery_t1d = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_chery_t1d.setGeometry(QtCore.QRect(10, 30, 131, 16))
        self.radioButton_chery_t1d.setObjectName("radioButton_chery_t1d")
        self.radioButton_chery_ctcs = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_chery_ctcs.setGeometry(QtCore.QRect(10, 60, 89, 16))
        self.radioButton_chery_ctcs.setObjectName("radioButton_chery_ctcs")
        self.label_13 = QtWidgets.QLabel(self.page_car_action)
        self.label_13.setGeometry(QtCore.QRect(160, 0, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.textEdit_car_led_state = QtWidgets.QTextEdit(self.page_car_action)
        self.textEdit_car_led_state.setGeometry(QtCore.QRect(260, 70, 221, 81))
        self.textEdit_car_led_state.setObjectName("textEdit_car_led_state")
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_car_action)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 490, 481, 111))
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButton_self_test = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_self_test.setGeometry(QtCore.QRect(320, 50, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_self_test.setFont(font)
        self.pushButton_self_test.setObjectName("pushButton_self_test")
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setGeometry(QtCore.QRect(320, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_car_action)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 150, 481, 331))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_right_led_sw = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_right_led_sw.setGeometry(QtCore.QRect(320, 260, 91, 61))
        self.groupBox_right_led_sw.setObjectName("groupBox_right_led_sw")
        self.radioButton_right_led_on = QtWidgets.QRadioButton(self.groupBox_right_led_sw)
        self.radioButton_right_led_on.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.radioButton_right_led_on.setObjectName("radioButton_right_led_on")
        self.radioButton_right_led_off = QtWidgets.QRadioButton(self.groupBox_right_led_sw)
        self.radioButton_right_led_off.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.radioButton_right_led_off.setObjectName("radioButton_right_led_off")
        self.groupBox_left_led_sw = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_left_led_sw.setGeometry(QtCore.QRect(320, 20, 91, 61))
        self.groupBox_left_led_sw.setObjectName("groupBox_left_led_sw")
        self.radioButton_left_led_on = QtWidgets.QRadioButton(self.groupBox_left_led_sw)
        self.radioButton_left_led_on.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.radioButton_left_led_on.setObjectName("radioButton_left_led_on")
        self.radioButton_left_led_off = QtWidgets.QRadioButton(self.groupBox_left_led_sw)
        self.radioButton_left_led_off.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.radioButton_left_led_off.setObjectName("radioButton_left_led_off")
        self.groupBox_left_dow_sw = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_left_dow_sw.setGeometry(QtCore.QRect(170, 20, 91, 61))
        self.groupBox_left_dow_sw.setObjectName("groupBox_left_dow_sw")
        self.radioButton_left_dow_on = QtWidgets.QRadioButton(self.groupBox_left_dow_sw)
        self.radioButton_left_dow_on.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.radioButton_left_dow_on.setObjectName("radioButton_left_dow_on")
        self.radioButton_left_dow_off = QtWidgets.QRadioButton(self.groupBox_left_dow_sw)
        self.radioButton_left_dow_off.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.radioButton_left_dow_off.setObjectName("radioButton_left_dow_off")
        self.label_show_car = QtWidgets.QLabel(self.groupBox_2)
        self.label_show_car.setGeometry(QtCore.QRect(50, 90, 361, 161))
        self.label_show_car.setObjectName("label_show_car")
        self.groupBox_right_dow_sw = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_right_dow_sw.setGeometry(QtCore.QRect(170, 260, 91, 61))
        self.groupBox_right_dow_sw.setObjectName("groupBox_right_dow_sw")
        self.radioButton_right_dow_on = QtWidgets.QRadioButton(self.groupBox_right_dow_sw)
        self.radioButton_right_dow_on.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.radioButton_right_dow_on.setObjectName("radioButton_right_dow_on")
        self.radioButton_right_dow_off = QtWidgets.QRadioButton(self.groupBox_right_dow_sw)
        self.radioButton_right_dow_off.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.radioButton_right_dow_off.setObjectName("radioButton_right_dow_off")
        self.groupBox_car_match = QtWidgets.QGroupBox(self.page_car_action)
        self.groupBox_car_match.setGeometry(QtCore.QRect(130, 59, 120, 91))
        self.groupBox_car_match.setObjectName("groupBox_car_match")
        self.radioButton_high_match = QtWidgets.QRadioButton(self.groupBox_car_match)
        self.radioButton_high_match.setGeometry(QtCore.QRect(10, 30, 89, 16))
        self.radioButton_high_match.setObjectName("radioButton_high_match")
        self.radioButton_low_match = QtWidgets.QRadioButton(self.groupBox_car_match)
        self.radioButton_low_match.setGeometry(QtCore.QRect(10, 60, 89, 16))
        self.radioButton_low_match.setObjectName("radioButton_low_match")
        self.stackedWidget.addWidget(self.page_car_action)
        self.page_version = QtWidgets.QWidget()
        self.page_version.setObjectName("page_version")
        self.pushButton_select_version_file = QtWidgets.QPushButton(self.page_version)
        self.pushButton_select_version_file.setGeometry(QtCore.QRect(340, 40, 131, 41))
        self.pushButton_select_version_file.setObjectName("pushButton_select_version_file")
        self.lineEdit_show_version_file = QtWidgets.QLineEdit(self.page_version)
        self.lineEdit_show_version_file.setGeometry(QtCore.QRect(20, 40, 301, 41))
        self.lineEdit_show_version_file.setObjectName("lineEdit_show_version_file")
        self.pushButton_read_write_version = QtWidgets.QPushButton(self.page_version)
        self.pushButton_read_write_version.setGeometry(QtCore.QRect(340, 100, 131, 41))
        self.pushButton_read_write_version.setObjectName("pushButton_read_write_version")
        self.stackedWidget.addWidget(self.page_version)
        self.page_diagnostic_information = QtWidgets.QWidget()
        self.page_diagnostic_information.setObjectName("page_diagnostic_information")
        self.label_24 = QtWidgets.QLabel(self.page_diagnostic_information)
        self.label_24.setGeometry(QtCore.QRect(10, 10, 441, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.groupBox_16 = QtWidgets.QGroupBox(self.page_diagnostic_information)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 70, 471, 71))
        self.groupBox_16.setObjectName("groupBox_16")
        self.radioButton_dtc_chery = QtWidgets.QRadioButton(self.groupBox_16)
        self.radioButton_dtc_chery.setGeometry(QtCore.QRect(20, 30, 89, 16))
        self.radioButton_dtc_chery.setObjectName("radioButton_dtc_chery")
        self.radioButton_dtc_ctcs = QtWidgets.QRadioButton(self.groupBox_16)
        self.radioButton_dtc_ctcs.setGeometry(QtCore.QRect(160, 30, 89, 16))
        self.radioButton_dtc_ctcs.setObjectName("radioButton_dtc_ctcs")
        self.groupBox_19 = QtWidgets.QGroupBox(self.page_diagnostic_information)
        self.groupBox_19.setGeometry(QtCore.QRect(10, 160, 471, 411))
        self.groupBox_19.setObjectName("groupBox_19")
        self.pushButton_dtc_info = QtWidgets.QPushButton(self.groupBox_19)
        self.pushButton_dtc_info.setGeometry(QtCore.QRect(180, 270, 281, 51))
        self.pushButton_dtc_info.setObjectName("pushButton_dtc_info")
        self.textBrowser_dtc_info = QtWidgets.QTextBrowser(self.groupBox_19)
        self.textBrowser_dtc_info.setGeometry(QtCore.QRect(20, 30, 441, 191))
        self.textBrowser_dtc_info.setObjectName("textBrowser_dtc_info")
        self.stackedWidget.addWidget(self.page_diagnostic_information)
        self.page_release_file_format_check = QtWidgets.QWidget()
        self.page_release_file_format_check.setObjectName("page_release_file_format_check")
        self.groupBox_13 = QtWidgets.QGroupBox(self.page_release_file_format_check)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 60, 461, 501))
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.pushButton_cali_select = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_cali_select.setGeometry(QtCore.QRect(360, 300, 91, 41))
        self.pushButton_cali_select.setObjectName("pushButton_cali_select")
        self.textEdit_file_format_show = QtWidgets.QTextEdit(self.groupBox_13)
        self.textEdit_file_format_show.setGeometry(QtCore.QRect(10, 20, 441, 201))
        self.textEdit_file_format_show.setObjectName("textEdit_file_format_show")
        self.pushButton_flash_driver_select = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_flash_driver_select.setGeometry(QtCore.QRect(360, 240, 91, 41))
        self.pushButton_flash_driver_select.setObjectName("pushButton_flash_driver_select")
        self.pushButton_app_select = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_app_select.setGeometry(QtCore.QRect(360, 360, 91, 41))
        self.pushButton_app_select.setObjectName("pushButton_app_select")
        self.lineEdit_flash_driver_address = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_flash_driver_address.setGeometry(QtCore.QRect(10, 240, 341, 41))
        self.lineEdit_flash_driver_address.setObjectName("lineEdit_flash_driver_address")
        self.lineEdit_cali_address = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_cali_address.setGeometry(QtCore.QRect(10, 301, 341, 41))
        self.lineEdit_cali_address.setObjectName("lineEdit_cali_address")
        self.lineEdit_app_address = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_app_address.setGeometry(QtCore.QRect(10, 360, 341, 41))
        self.lineEdit_app_address.setObjectName("lineEdit_app_address")
        self.label_3 = QtWidgets.QLabel(self.page_release_file_format_check)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_release_file_format_check)
        self.groupBox_bus_status = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_bus_status.setGeometry(QtCore.QRect(650, 540, 441, 101))
        self.groupBox_bus_status.setObjectName("groupBox_bus_status")
        self.pushButton_bus_on = QtWidgets.QPushButton(self.groupBox_bus_status)
        self.pushButton_bus_on.setGeometry(QtCore.QRect(10, 20, 71, 61))
        self.pushButton_bus_on.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/bus_on.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton_bus_on.setIcon(icon)
        self.pushButton_bus_on.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_bus_on.setCheckable(False)
        self.pushButton_bus_on.setAutoDefault(False)
        self.pushButton_bus_on.setDefault(False)
        self.pushButton_bus_on.setFlat(True)
        self.pushButton_bus_on.setObjectName("pushButton_bus_on")
        self.pushButton_bus_off = QtWidgets.QPushButton(self.groupBox_bus_status)
        self.pushButton_bus_off.setGeometry(QtCore.QRect(90, 20, 71, 61))
        self.pushButton_bus_off.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/bus_off.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton_bus_off.setIcon(icon1)
        self.pushButton_bus_off.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_bus_off.setFlat(True)
        self.pushButton_bus_off.setObjectName("pushButton_bus_off")
        self.label_17 = QtWidgets.QLabel(self.groupBox_bus_status)
        self.label_17.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.label_17.setObjectName("label_17")
        self.label_23 = QtWidgets.QLabel(self.groupBox_bus_status)
        self.label_23.setGeometry(QtCore.QRect(90, 80, 71, 16))
        self.label_23.setObjectName("label_23")
        self.textBrowser_bus_status = QtWidgets.QTextBrowser(self.groupBox_bus_status)
        self.textBrowser_bus_status.setGeometry(QtCore.QRect(180, 20, 251, 71))
        self.textBrowser_bus_status.setObjectName("textBrowser_bus_status")
        self.textEdit_show_result = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_show_result.setGeometry(QtCore.QRect(650, 40, 441, 491))
        self.textEdit_show_result.setObjectName("textEdit_show_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CAN-AUTO-TEST"))
        self.pushButton_diva.setText(_translate("MainWindow", "DIVA"))
        self.pushButton_diagnosis.setText(_translate("MainWindow", "诊断测试"))
        self.pushButton_nm.setText(_translate("MainWindow", "网管测试"))
        self.pushButton_signal.setText(_translate("MainWindow", "CAN信号测试"))
        self.label.setText(_translate("MainWindow", "      功能项"))
        self.pushButton_read_version.setText(_translate("MainWindow", "一键版本信息"))
        self.pushButton_car_scene.setText(_translate("MainWindow", "实车节点模拟"))
        self.pushButton_car_action.setText(_translate("MainWindow", "实车动作测试"))
        self.pushButton_release_file_format_check.setText(_translate("MainWindow", "文件格式检查"))
        self.pushButton_car_dtc.setText(_translate("MainWindow", "一键故障信息"))
        self.comboBox_function.setItemText(0, _translate("MainWindow", "1.Format"))
        self.comboBox_function.setItemText(1, _translate("MainWindow", "2.DataContent"))
        self.comboBox_function.setItemText(2, _translate("MainWindow", "3.Application"))
        self.comboBox_function.setItemText(3, _translate("MainWindow", "4.SecurityAccess"))
        self.comboBox_function.setItemText(4, _translate("MainWindow", "5.General"))
        self.comboBox_function.setItemText(5, _translate("MainWindow", "6.FunctionalAddressing"))
        self.comboBox_function.setItemText(6, _translate("MainWindow", "7.Transport_Layer"))
        self.pushButton_diva_test.setText(_translate("MainWindow", "TEST"))
        self.groupBox.setTitle(_translate("MainWindow", "评价系统"))
        self.label_6.setText(_translate("MainWindow", "总计"))
        self.label_7.setText(_translate("MainWindow", "通过"))
        self.label_8.setText(_translate("MainWindow", "错误"))
        self.pushButton_diva_select.setText(_translate("MainWindow", "SELECT"))
        self.pushButton_load_kvaser_file.setText(_translate("MainWindow", "加载kvaser文件"))
        self.label_9.setText(_translate("MainWindow", "加载kvaser录的数据，模拟整车节点数据"))
        self.label_10.setText(_translate("MainWindow", "过滤应用报文："))
        self.label_11.setText(_translate("MainWindow", "过滤网管报文："))
        self.pushButton_read_file.setText(_translate("MainWindow", "回读"))
        self.groupBox_3.setTitle(_translate("MainWindow", "会话模式-$10"))
        self.comboBox_diag_session.setItemText(0, _translate("MainWindow", "$01 Default Session"))
        self.comboBox_diag_session.setItemText(1, _translate("MainWindow", "$02 Programming Session"))
        self.comboBox_diag_session.setItemText(2, _translate("MainWindow", "$03 Extended Session"))
        self.comboBox_diag_session.setItemText(3, _translate("MainWindow", "$41 Coding Session"))
        self.pushButton_diag_session.setText(_translate("MainWindow", "Session"))
        self.groupBox_4.setTitle(_translate("MainWindow", "安全服务-$27"))
        self.comboBox_diag_request_seed.setItemText(0, _translate("MainWindow", "$01 Request Seed (Level 1)"))
        self.comboBox_diag_request_seed.setItemText(1, _translate("MainWindow", "$03 Request Seed (Level 2)"))
        self.comboBox_diag_request_seed.setItemText(2, _translate("MainWindow", "$05 Request Seed (Level 3)"))
        self.comboBox_diag_request_seed.setItemText(3, _translate("MainWindow", "$07 Request Seed (Level 4)"))
        self.pushButton_diag_request_seed.setText(_translate("MainWindow", "RequestSeed"))
        self.comboBox_diag_send_key.setItemText(0, _translate("MainWindow", "$02 Seed Key     (Level 1)"))
        self.comboBox_diag_send_key.setItemText(1, _translate("MainWindow", "$04 Seed Key     (Level 2)"))
        self.comboBox_diag_send_key.setItemText(2, _translate("MainWindow", "$06 Seed Key     (Level 3)"))
        self.comboBox_diag_send_key.setItemText(3, _translate("MainWindow", "$08 Seed Key     (Level 4)"))
        self.pushButton_diag_send_key.setText(_translate("MainWindow", "SendKey"))
        self.groupBox_5.setTitle(_translate("MainWindow", "通用-$11 $14 $19 $22 $28 $2E $2F $31 $3E $85"))
        self.comboBox_diag_other_service.setItemText(0, _translate("MainWindow", "$11 ECU Reset"))
        self.comboBox_diag_other_service.setItemText(1, _translate("MainWindow", "$14 ClearDiagnosticInformation"))
        self.comboBox_diag_other_service.setItemText(2, _translate("MainWindow", "$19 ReadDTCInformation"))
        self.comboBox_diag_other_service.setItemText(3, _translate("MainWindow", "$22 ReadDataByIdentifier"))
        self.comboBox_diag_other_service.setItemText(4, _translate("MainWindow", "$28 CommunicationControl"))
        self.comboBox_diag_other_service.setItemText(5, _translate("MainWindow", "$2E WriteDataByIdentifier"))
        self.comboBox_diag_other_service.setItemText(6, _translate("MainWindow", "$2F InputOutputControlByIdentifier"))
        self.comboBox_diag_other_service.setItemText(7, _translate("MainWindow", "$31 RoutineControl"))
        self.comboBox_diag_other_service.setItemText(8, _translate("MainWindow", "$3E TesterPresent"))
        self.comboBox_diag_other_service.setItemText(9, _translate("MainWindow", "$85 ControlDTCSetting"))
        self.pushButton_diag_send_service.setText(_translate("MainWindow", "Start"))
        self.groupBox_8.setTitle(_translate("MainWindow", "显示"))
        self.label_diag_title.setText(_translate("MainWindow", "配置信息"))
        self.pushButton_diag_configer_file.setText(_translate("MainWindow", "加载配置信息"))
        self.radioButton_phy_address.setText(_translate("MainWindow", "物理寻址"))
        self.radioButton_device_online.setText(_translate("MainWindow", "设备在线"))
        self.label_4.setText(_translate("MainWindow", "这个页面是网络测试用的"))
        self.groupBox_chery_sw.setTitle(_translate("MainWindow", "奇瑞乘用车系列"))
        self.radioButton_dow_off.setText(_translate("MainWindow", "DOW_OFF"))
        self.radioButton_dow_on.setText(_translate("MainWindow", "DOW_ON"))
        self.label_19.setText(_translate("MainWindow", "DOW_SW:"))
        self.radioButton_rcw_off.setText(_translate("MainWindow", "RCW_OFF"))
        self.radioButton_rcw_on.setText(_translate("MainWindow", "RCW_ON"))
        self.label_18.setText(_translate("MainWindow", "RCW_SW:"))
        self.radioButton_bsd_off.setText(_translate("MainWindow", "BSD_OFF"))
        self.radioButton_bsd_on.setText(_translate("MainWindow", "BSD_ON"))
        self.label_15.setText(_translate("MainWindow", "BSD_SW:"))
        self.pushButton_send_ihu_sw.setText(_translate("MainWindow", "设置大屏开关"))
        self.groupBox_ctcs_sw.setTitle(_translate("MainWindow", "CTCS系列"))
        self.radioButton_ctcs_dow_off.setText(_translate("MainWindow", "DOW_OFF"))
        self.radioButton_ctcs_dow_on.setText(_translate("MainWindow", "DOW_ON"))
        self.label_20.setText(_translate("MainWindow", "DOW_SW:"))
        self.radioButton_ctcs_cvw_off.setText(_translate("MainWindow", "CVW_OFF"))
        self.radioButton_ctcs_cvw_on.setText(_translate("MainWindow", "CVW_ON"))
        self.label_21.setText(_translate("MainWindow", "CVW_SW:"))
        self.radioButton_ctcs_bsd_off.setText(_translate("MainWindow", "BSD_OFF"))
        self.radioButton_ctcs_bsd_on.setText(_translate("MainWindow", "BSD_ON"))
        self.label_16.setText(_translate("MainWindow", "BSD_SW:"))
        self.pushButton_send_ctcs_ihu_sw.setText(_translate("MainWindow", "设置大屏开关"))
        self.radioButton_ctcs_rcw_off.setText(_translate("MainWindow", "RCW_OFF"))
        self.radioButton_ctcs_rcw_on.setText(_translate("MainWindow", "RCW_ON"))
        self.label_22.setText(_translate("MainWindow", "RCW_SW:"))
        self.label_5.setText(_translate("MainWindow", "显示大屏开关状态信息"))
        self.groupBox_18.setTitle(_translate("MainWindow", "车型"))
        self.radioButton_chery_t1d_2.setText(_translate("MainWindow", "奇瑞乘用车系列"))
        self.radioButton_chery_ctcs_2.setText(_translate("MainWindow", "CTCS"))
        self.label_12.setText(_translate("MainWindow", "实车动作测试:"))
        self.groupBox_6.setTitle(_translate("MainWindow", "车型"))
        self.radioButton_chery_t1d.setText(_translate("MainWindow", "奇瑞乘用车系列"))
        self.radioButton_chery_ctcs.setText(_translate("MainWindow", "CTCS"))
        self.label_13.setText(_translate("MainWindow", "检查实车LED&DOW灯是否正常亮灭"))
        self.groupBox_7.setTitle(_translate("MainWindow", "自检模式"))
        self.pushButton_self_test.setText(_translate("MainWindow", "一键自检"))
        self.label_14.setText(_translate("MainWindow", "模拟上电状态"))
        self.groupBox_2.setTitle(_translate("MainWindow", "动作测试"))
        self.groupBox_right_led_sw.setTitle(_translate("MainWindow", "检查右LED开关"))
        self.radioButton_right_led_on.setText(_translate("MainWindow", "ON"))
        self.radioButton_right_led_off.setText(_translate("MainWindow", "OFF"))
        self.groupBox_left_led_sw.setTitle(_translate("MainWindow", "检查左LED开关"))
        self.radioButton_left_led_on.setText(_translate("MainWindow", "ON"))
        self.radioButton_left_led_off.setText(_translate("MainWindow", "OFF"))
        self.groupBox_left_dow_sw.setTitle(_translate("MainWindow", "检查左DOW开关"))
        self.radioButton_left_dow_on.setText(_translate("MainWindow", "ON"))
        self.radioButton_left_dow_off.setText(_translate("MainWindow", "OFF"))
        self.label_show_car.setText(_translate("MainWindow", "汽车展示图"))
        self.groupBox_right_dow_sw.setTitle(_translate("MainWindow", "检查右DOW开关"))
        self.radioButton_right_dow_on.setText(_translate("MainWindow", "ON"))
        self.radioButton_right_dow_off.setText(_translate("MainWindow", "OFF"))
        self.groupBox_car_match.setTitle(_translate("MainWindow", "配置信息"))
        self.radioButton_high_match.setText(_translate("MainWindow", "高配"))
        self.radioButton_low_match.setText(_translate("MainWindow", "低配"))
        self.pushButton_select_version_file.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_read_write_version.setText(_translate("MainWindow", "读写版本信息"))
        self.label_24.setText(_translate("MainWindow", "读取故障信息"))
        self.groupBox_16.setTitle(_translate("MainWindow", "车系选择"))
        self.radioButton_dtc_chery.setText(_translate("MainWindow", "奇瑞乘用车系列"))
        self.radioButton_dtc_ctcs.setText(_translate("MainWindow", "CTCS"))
        self.groupBox_19.setTitle(_translate("MainWindow", "故障信息读取"))
        self.pushButton_dtc_info.setText(_translate("MainWindow", "读取故障信息"))
        self.pushButton_cali_select.setText(_translate("MainWindow", "参数文件"))
        self.pushButton_flash_driver_select.setText(_translate("MainWindow", "驱动文件"))
        self.pushButton_app_select.setText(_translate("MainWindow", "应用文件"))
        self.label_3.setText(_translate("MainWindow", "释放文件格式检查"))
        self.groupBox_bus_status.setTitle(_translate("MainWindow", "Bus Status"))
        self.label_17.setText(_translate("MainWindow", "   Start"))
        self.label_23.setText(_translate("MainWindow", "    Stop"))
import bus_off_rc
import bus_on_rc
